server:
  port: 8888  
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://Rick_BN@bitbucket.org/Rick_BN/config-data.git
          search-paths: api
          default-label: "master"
          
  security:
    user:
      name: root
      password: adminadmin
